//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial.ClassLib1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int RollNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> Subject1 { get; set; }
        public Nullable<decimal> Subject2 { get; set; }
        public Nullable<decimal> Subject3 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Per { get; set; }
        public string Res { get; set; }
    }
}
